server:
  port: 80

spring:
  application:
    #服务别名-注册Consul到注册中心名称
    name: consul-consumer-order

  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        service-name: ${spring.application.name}