server:
  port: 8001

spring:
  application:
    name: cloud-payment-service
  #    zipkin:
  #      base-url: http://localhost:9411
  #    sleuth:
  #      sampler:
  #        #采样取值介于 0到1之间，1则表示全部收集
  #        probability: 1
  datasource:
    # 当前数据源操作类型
    type: com.alibaba.druid.pool.DruidDataSource
    # mysql驱动类
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/cloud?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password: 142822

eureka:
  client:
    #将自己注册进eureka server 默认为true
    register-with-eureka: true
    #是否从eureka server抓取已有的注册信息,默认为true,单节点无所谓,集群必须设置为true 才能配合ribbon使用负载均衡
    fetch-registry: true
    service-url:
      defaultZone: http://eureka7001:7001/eureka,http://eureka7002:7002/eureka
  instance:
    instance-id: payment-8001
    prefer-ip-address: true

mybatis:
  mapper-locations: classpath*:mapper/*.xml
  type-aliases-package: com.simmon.springcloud.entities