server:
  port: 80

spring:
  application:
    name: cloud-order-service

eureka:
  client:
    #将自己注册进eureka server 默认为true
    register-with-eureka: false
    #是否从eureka server抓取已有的注册信息,默认为true,单节点无所谓,集群必须设置为true 才能配合ribbon使用负载均衡
    fetch-registry: true
    service-url:
     defaultZone: http://eureka7001:7001/eureka,http://eureka7002:7002/eureka
#设置feign客户端超时时间 (open肺功能默认支持ribbon)
ribbon:
  #指的是建立连接所用的时间 ,适用于网络状况正常的情况下,两端连接所用的时间
  ReadTimeOut: 5000
  #指的是建立连接后从服务器读取可用资源所用的时间
  ConnectTimeout: 5000